<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Xal\Xal.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="ComparableExtensionsTests.cs" />
    </ItemGroup>

	<ItemGroup>
		<PackageReference Include="MSTest" />
	</ItemGroup>
	
	
</Project>
