<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Version>2.0.0</Version>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Authors>Alexandre Toledo Perez</Authors>
		<Description>A utility library for .NET</Description>
		<Copyright>Copyright (c) 2018-$([System.DateTime]::Now.ToString('yyyy')) Alexandre Toledo Perez</Copyright>
		<PackageId>$(AssemblyName)</PackageId>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/alexandretperez/Xal</PackageProjectUrl>
		<RepositoryUrl>https://github.com/alexandretperez/Xal</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>C# .NET Library</PackageTags>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Data\**" />
	  <Compile Remove="Extensions\**" />
	  <Compile Remove="Security\**" />
	  <Compile Remove="Util\**" />
	  <EmbeddedResource Remove="Data\**" />
	  <EmbeddedResource Remove="Extensions\**" />
	  <EmbeddedResource Remove="Security\**" />
	  <EmbeddedResource Remove="Util\**" />
	  <None Remove="Data\**" />
	  <None Remove="Extensions\**" />
	  <None Remove="Security\**" />
	  <None Remove="Util\**" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Remove="DateSpecification.cs" />
	  <Compile Remove="DateTimeEventArgs.cs" />
	  <Compile Remove="GZip.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" />
	</ItemGroup>

</Project>