<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>

		<Authors>Alexandre Toledo Perez</Authors>
		<Description>A concise library of .NET extension members</Description>
		<Copyright>Copyright (c) 2018-$([System.DateTime]::Now.ToString('yyyy')) Alexandre Toledo Perez</Copyright>

		<PackageId>$(AssemblyName)</PackageId>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/alexandretperez/Xal</PackageProjectUrl>

		<RepositoryUrl>https://github.com/alexandretperez/Xal</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>

		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<PackageTags>C# .NET Library Extension</PackageTags>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>

		<Nullable>enable</Nullable>
		<LangVersion>14.0</LangVersion>

		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<PackageIcon>icon.png</PackageIcon>
	
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub"
                          PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup>
		<None Include="../readme.md"
              Pack="true"
              PackagePath="\" />

		<None Include="../icon.png"
              Pack="true"
              PackagePath="\" />
	</ItemGroup>
</Project>