name: Xal - Publish NuGet

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      PROJECT: ./Xal/Xal.csproj
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Restore
        run: dotnet restore $PROJECT
        working-directory: ${{ github.workspace }}

      - name: Build
        run: dotnet build $PROJECT -c Release --no-restore
        working-directory: ${{ github.workspace }}

      - name: Ensure Package folder exists
        run: mkdir -p ${{ github.workspace }}/Package

      - name: Pack
        run: dotnet pack $PROJECT -c Release --no-build -o ${{ github.workspace }}/Package /p:PackageVersion=${GITHUB_REF_NAME#v}
        working-directory: ${{ github.workspace }}
         
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ vars.NUGET_USER }}
             
      - name: Push NuGet package
        run: dotnet nuget push "${{ github.workspace }}/Package/Xal.*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --skip-duplicate

      - name: Push symbols package
        run: dotnet nuget push "${{ github.workspace }}/Package/Xal.*.snupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --skip-duplicate